### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by psikoz** [limitedeternity/TextReader#8]
Hey @limitedeternity  i designed a  logo for textreader. Logo idea;

- I used a microphone to represent the ''reader'' function.
- I added text icon next to the microphone.
- Text nodes represent the electron logo.

WDYT?

![tr](https://user-images.githubusercontent.com/40601249/42954069-74093e2c-8b84-11e8-9a2a-dde81a311cc2.jpg)

**Comment by limitedeternity** [comment]
Fourth one is really great! Do you have png assets for this icon?

**Comment by psikoz** [comment]
Ofcourse, I will provide all files as soon as possible. Along with other variations. How are these?

![2](https://user-images.githubusercontent.com/40601249/43003813-66e57c1c-8c36-11e8-8158-ce3f6aa77d9a.jpg)

**Comment by limitedeternity** [comment]
Hmm, first variant's font weight seems too bold for me. Second variant is good, but I think there could be a bit more space between logo and text.

**Comment by psikoz** [comment]
Hmm, are these?

![3](https://user-images.githubusercontent.com/40601249/43004426-66ced9ba-8c38-11e8-98dc-cdbaec0366d0.jpg)

**Comment by limitedeternity** [comment]
Yep, like that. Now I like both variants lol.

**Comment by psikoz** [comment]
I will send a pr for all variations as soon as possible :)

**Comment by limitedeternity** [comment]
K, will look forward to it

**Comment by limitedeternity** [comment]
Thanks, everything merged!
